### PR TITLE
unit tests + small RoBMA fixes

### PR DESCRIPTION
**Pull request by FBartos**

### CODE REVIEW

**Comment by FBartos** [comment]
The PR contains unit tests for the whole meta-analysis module + some fixes to RoBMA (mirrors: https://github.com/jasp-stats/jasp-desktop/pull/4261)

**Comment by TimKDJ** [comment]
Are all the changes -- besides the unit tests -- already incorporated in jasp-desktop/stable?

**Comment by FBartos** [comment]
no, the additional changes are part of this:
https://github.com/jasp-stats/jasp-desktop/pull/4261

**Comment by TimKDJ** [comment]
Ah you mentioned that right above my comment ^.^
I will wait until that one is reviewed and merged

**Comment by FBartos** [comment]
adding updates from:
https://github.com/jasp-stats/jasp-desktop/pull/4239#issuecomment-687181912

**Comment by FBartos** [comment]
also fixes: https://github.com/jasp-stats/INTERNAL-jasp/issues/1042#event-3750311500

**Pull request merged**
